name: pipeline

on:
  push:
    branches: [main]

jobs:
  buildx:
    uses: guilhermelinosp/ci-templates/.github/workflows/buildx.yml@main
    secrets: inherit


  release:
    secrets: inherit
    needs: [buildx]
    uses: guilhermelinosp/ci-templates/.github/workflows/release.yml@main

  push:
    needs: [buildx, release]
    uses: guilhermelinosp/ci-templates/.github/workflows/push.yml@main
    secrets: inherit
    with:
      image: ${{ needs.buildx.outputs.image }}
      version: ${{ needs.release.outputs.version }}
